sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: dbroot
    password: mysql_password
  rustfs:
    endpoint: "http://localhost:9000"
    access-key: "rustfsadmin"
    secret-key: "rustfsadmin"
    region: "sky"
    # 💡 2. 核心修复：将 bucked 修改为标准的 bucket
    bucket-name: "sky-data-lake"
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 9